### ISSUE TITLE
Error downloading Trained model

### ISSUE THREAD

**Issue by mapo80** [Aftaab99/OfflineSignatureVerification#38]
Hi,

there's an error download trained model.
This is the error:
`python DownloadData.py
Downloading dataset...
Extracting data...
Traceback (most recent call last):
  File "/Users/politom/Downloads/OfflineSignatureVerification-master/DownloadData.py", line 55, in <module>
    extract('./Datasets/cedar1.zip')
  File "/Users/politom/Downloads/OfflineSignatureVerification-master/DownloadData.py", line 39, in extract
    zip_ref = zipfile.ZipFile(file_path, 'r')
  File "/Users/politom/.pyenv/versions/3.10.4/lib/python3.10/zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "/Users/politom/.pyenv/versions/3.10.4/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file`

Can you restore file download?

Thanks you for all your work. Great job.

**Comment by sreeshanth00** [comment]
Actually i had similar problem with both dataset and pre-trained model 
The thing is due to security reason by drive (file is too large to scan for virus) download.py creates folders but file isn't downloaded 

you can just manually download files using their ID's

for Model use :
 [https://drive.google.com/file/d/1Dt-np-v30w0X1OSqqcKpzvifktq4k7r-](url)

for Dataset use:
[https://drive.google.com/file/d/1w2DEYX2pBhBNS2l4sqrl8j-Am4cNSBoZ](url)

**Comment by Aftaab99** [comment]
This should be fixed now, used `gdown` instead as earlier code to download the files isnt working anymore.

**Comment by Aftaab99** [comment]
This should be fixed now, used gdown instead as earlier code to download the files isnt working anymore.
